cloud:
  aws:
    credentials:
      access-key: AKIA6AAVLK3ZR7DJEF7V
      secret-key: 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
    region:
      static: eu-west-1
    stack:
      auto: false

application:
  bucket:
    name: assignment2adventerprise



server:
  port: 8080
