cloud:
  aws:
    credentials:
      access-key: HIDEKEYONLINE  
      secret-key: HIDEKEYONLINE
    region:
      static: eu-west-1
    stack:
      auto: false

application:
  bucket:
    name: assignment2adventerprise



server:
  port: 8080
